### ISSUE TITLE
SemVer code of conduct

### ISSUE THREAD

**Issue by Aspie96** [paradite/github-dramas#2]
Hi!

I don't know in what year this belongs, since two years are relevant.

Here, a user suggested a code of conduct: https://github.com/semver/semver/pull/419

Years later, it got used against them for merely disagreing with maintainers on anohter CoC operation: https://github.com/semver/semver/issues/571

It didn't get much attention, but I think it can belong here (expecially given how well-known SemVer is).

**Comment by paradite** [comment]
Good attempt, but not drama enough.
